'use strict';
const hotels = [
 {name:'武雄・湯元莊東洋館',en:'YUMOTOSO TOYOKAN',dates:'10.24 — 10.26',nights:2,img:'toyokan.jpg',alt:'東洋館白色外牆與枝垂櫻裝飾，官方照片',room:'「藤」和室・雙人床',meals:'兩晚夕朝食・佐賀牛陶板燒方案',price:101200,payment:'到店付款',check:'15:00 入住 / 11:00 退房',note:'前兩晚都留在武雄。晚餐時段請入住時確認。',query:'湯元荘 東洋館 武雄',url:'https://takeo-toyokan.jp/'},
 {name:'長崎・花園露台酒店',en:'GARDEN TERRACE NAGASAKI',dates:'10.26 — 10.28',nights:2,img:'nagasaki.jpg',alt:'長崎港灣夜景，目的地示意，非指定房型',room:'離棟海景套房・雙床',meals:'含早餐',price:73010,payment:'已付款・8/27 收據',check:'16:00 入住 / 12:00 退房',note:'8/25 起取消收全額。接駁時刻與房間視野請向飯店確認。',query:'Garden Terrace Nagasaki Hotel Resort',url:'https://www.gt-nagasaki.jp/'},
 {name:'豪斯登堡・森林小屋',en:'FOREST VILLA',dates:'10.28 — 10.30',nights:2,img:'forestvilla.jpg',alt:'豪斯登堡湖畔森林別墅，沿用原專案配圖',room:'湖畔別墅・兩人入住',meals:'含早餐',price:58800,payment:'已刷卡付訖',check:'入住與退房時刻待飯店確認',note:'保留兩晚。確認信的 00:00 是預計抵達欄位，不能當成正式入住時間。',query:'Huis Ten Bosch Forest Villa',url:'https://www.huistenbosch.co.jp/hotels/fv/'},
 {name:'豪斯登堡・米菲兔房',en:'HOTEL AMSTERDAM',dates:'10.30 — 10.31',nights:1,img:'amsterdamhotel.jpg',alt:'豪斯登堡阿姆斯特丹飯店廣場，沿用原專案配圖',room:'米菲兔基本房型',meals:'含早餐與米菲兔備品',price:69200,payment:'已刷卡付訖',check:'入住與退房時刻待飯店確認',note:'只換這一次房，把最後一晚留給園區中央。',query:'Huis Ten Bosch Hotel Amsterdam',url:'https://www.huistenbosch.co.jp/hotels/am/'},
 {name:'福岡・博多新大谷',en:'HOTEL NEW OTANI HAKATA',dates:'10.31 — 11.02',nights:2,img:'newotani.jpg',alt:'博多新大谷飯店外觀，官方照片',room:'行政雙人房・禁菸・高樓層',meals:'不含早餐',price:55008,payment:'到店付款',check:'14:00–24:00 入住 / 11:00 退房',note:'渡邊通站步行約 1 分鐘。連住兩晚，11/01 不搬飯店。',query:'Hotel New Otani Hakata',url:'https://www.kys-newotani.co.jp/hakata/'}
];
const days = [
 {date:'10.24',week:'六',city:'武雄',en:'TAKEO',title:'抵達後，<br>把步調交給溫泉。',image:'toyokan.jpg',alt:'武雄湯元莊東洋館官方外觀照片',hotel:0,intro:'落地後不在福岡停留，直接前往武雄溫泉。午餐、神社、入住與旅館晚餐，第一天維持輕鬆。',route:'福岡國際線 → 武雄溫泉站 → 武雄神社 → 東洋館',map:'湯元荘 東洋館 武雄',steps:[['06:35','長榮 BR104 起飛','桃園第二航廈出發；09:55 抵達福岡國際線，時間為當地時間。','已開票'],['中午','前往武雄溫泉站吃午餐','入境後經博多轉乘，直接往武雄；抵達後先在車站周邊用餐，班次依入境進度選擇。','規劃','武雄温泉駅'],['午後','武雄神社與大楠','午餐後前往武雄神社，沿竹林小徑看大楠；帶著行李時可先寄放或搭計程車。','確認','武雄神社'],['15:00 後','東洋館入住','已訂「藤」和室雙人床，逛完神社後辦理入住。','已訂','湯元荘 東洋館 武雄'],['晚間','佐賀牛陶板燒與泡湯','使用已訂一泊二食方案；用餐時間向旅館確認，今晚不用再找餐廳。','含餐','湯元荘 東洋館 武雄']],note:'福岡到武雄仍需依班次在博多轉乘；「直接前往」指不在福岡安排觀光。帶大行李時以寄放或計程車銜接神社較輕鬆。'},
 {date:'10.25',week:'日',city:'武雄・有田',en:'TAKEO & ARITA',title:'溫泉散步，<br>再去挑一只好器。',image:'toyokan-bath.jpg',alt:'東洋館官方空間照片，窗外為武雄溫泉樓門；非已訂藤房型',hotel:0,intro:'早餐後在武雄溫泉散步，再前往有田瓷器城（アリタセラ）逛陶瓷店。傍晚回東洋館吃已包含的晚餐。',route:'東洋館 → 武雄溫泉樓門 → 有田瓷器城 → 東洋館',map:'アリタセラ',steps:[['早餐','在東洋館慢慢吃','早餐已包含在住宿裡，不趕第一班車。','含餐','湯元荘 東洋館 武雄'],['上午','武雄溫泉散步','從樓門與新館一帶慢慢散步；生肖導覽若想參加，出發前再確認場次。','確認','武雄温泉楼門'],['中午起','有田瓷器城（アリタセラ）','前往陶瓷器購物中心逛街採買；交通、午餐與回程時間待排定。','確認','アリタセラ'],['晚間','旅館晚餐與溫泉','使用東洋館已訂的一泊二食方案，採買後回武雄休息。','含餐','湯元荘 東洋館 武雄']],note:'原訂 10/25 18:30 的博多紀念日晚餐已於 9/14 確認取消；今天唯一還要補的是武雄—有田的實際交通時刻。'},
 {date:'10.26',week:'一',city:'長崎',en:'NAGASAKI',title:'離開湯煙，<br>走進港都街景。',image:'nagasaki.jpg',alt:'長崎港灣與城市夜景',hotel:1,intro:'早餐後從武雄前往長崎，在長崎站吃午餐，再逛大浦天主堂與市區；晚上暫定留在飯店吃飯。',route:'東洋館 → 長崎站 → 大浦天主堂 → 花園露台酒店',map:'Garden Terrace Nagasaki Hotel Resort',steps:[['早餐後','東洋館退房、前往長崎','最晚 11:00 退房；從武雄溫泉搭西九州新幹線前往長崎。','規劃','武雄温泉駅'],['中午','長崎站午餐','抵達後先在長崎站周邊吃午餐，行李寄放車站或洽飯店。','確認','長崎駅'],['午後','大浦天主堂與長崎市區','參觀大浦天主堂，再依時間與體力散步南山手、哥拉巴園周邊或市區。','確認','大浦天主堂'],['16:00','長崎花園露台入住','接駁時間事先詢問飯店；10/26–28 海景套房已訂。','已訂','Garden Terrace Nagasaki Hotel Resort'],['晚間','暫定在飯店吃晚餐','依你的新安排先保留飯店晚餐方向；目前沒有餐廳訂位或含晚餐紀錄，需再向飯店確認。','暫定','Garden Terrace Nagasaki Hotel Resort']],note:'飯店方案已確認含早餐，但未找到晚餐預訂；因此 10/26 晚餐清楚標成「暫定」，不列為已訂。'},
 {date:'10.27',week:'二',city:'長崎',en:'THE ISLAND & THE CITY',title:'上午出海，<br>午後讀一段歷史。',image:'gunkanjima.jpg',alt:'海上軍艦島與建築遺跡',hotel:1,intro:'上午登軍艦島，回市區吃午餐後前往長崎原爆資料館；19:00 到大阪屋濱町店吃已訂晚餐。',route:'飯店 → 軍艦島 → 市區午餐 → 原爆資料館 → 大阪屋',map:'軍艦島デジタルミュージアム',steps:[['08:30','查看業者海況通知','早餐與下山交通提前安排；大件行李留飯店。','提醒'],['09–10:00','軍艦島數位博物館報到','持 QR 碼換票；不是直接到碼頭報到。','已訂','軍艦島デジタルミュージアム'],['10:30','軍艦島出航','10:10 登船、10:20 前上船；常盤碼頭出航，預計 13:15 回港。','已訂','常盤2号桟橋 長崎'],['午後','市區午餐、長崎原爆資料館','回港後先在市區吃午餐，再前往資料館；午餐店家尚未指定。','確認','長崎原爆資料館'],['19:00','大阪屋濱町店晚餐','已收到訂位確認；套餐金額暫沿用 ¥11,000／人，需回平台核對。','已訂','大阪屋 浜町店 長崎']],note:'軍艦島能否上陸以當日海況為準；可能改為周遊或停航。午餐保留彈性，晚餐則已有確認。'},
 {date:'10.28',week:'三',city:'長崎・豪斯登堡',en:'NAGASAKI TO HUIS TEN BOSCH',title:'一盒長崎菓子，<br>接上園區長住。',image:'forestvilla.jpg',alt:'豪斯登堡森林小木屋與湖景',hotel:2,intro:'早餐後先去岩永梅壽軒排隊購買，再吃午餐、前往豪斯登堡；從今天下午一路待到 10/31 中午過後。',route:'花園露台 → 岩永梅壽軒 → 午餐 → 豪斯登堡',map:'Huis Ten Bosch Forest Villa',steps:[['早餐後','退房、前往岩永梅壽軒','12:00 前退房；先去店外排隊，熱門品項與當日供應以現場為準。','確認','岩永梅寿軒'],['中午','長崎市區午餐','買完菓子後在市區吃午餐，店家尚未指定。','自由'],['午後','前往豪斯登堡','午餐後搭車前往豪斯登堡，直達或轉乘以當日列車為準。','確認','ハウステンボス'],['入住後','森林小屋與園內晚餐','湖畔別墅已付兩晚；豪斯登堡期間的正餐都在園區內處理。','已訂','フォレストヴィラ ハウステンボス']],note:'10/28 午餐後至 10/31 中午過後都留在豪斯登堡；園內餐廳不先綁定，依遊玩位置、候位與當日營業處理。'},
 {date:'10.29',week:'四',city:'豪斯登堡',en:'A DAY WITH NO RUSH',title:'今天的待辦，<br>只有好好玩。',image:'huistenbosch.jpg',alt:'豪斯登堡歐式街景與花園',hotel:2,intro:'園內完整的一天。想玩的設施先去，午餐後回湖邊休息，等天暗下來再出門；用餐都在園內處理。',route:'森林小屋 → 園內設施 → 運河散步 → 森林小屋',map:'Huis Ten Bosch',steps:[['早餐後','選兩個最想玩的設施','入園時間與飯店提早入園特典需現場確認；先挑最在意的兩項。','規劃','ハウステンボス'],['中午','園內午餐與小店','午餐不指定餐廳，依當時所在區域與候位選擇。','自由'],['午後','回森林小屋歇一下','連住的好處是不用重新收行李，午休也算行程。','自由'],['夜間','園內晚餐與點燈散步','晚餐在園內處理，再挑一場當日確定演出的節目；雨天換室內體驗。','自由','ハウステンボス']],note:'萬聖節、玫瑰與夜間秀的具體檔期請看當天公告；餐廳同樣以 2026 當日營業資訊為準。'},
 {date:'10.30',week:'五',city:'豪斯登堡',en:'A LITTLE MIFFY DAY',title:'換一間房，<br>把可愛留一晚。',image:'amsterdamhotel.jpg',alt:'阿姆斯特丹飯店與園區廣場',hotel:3,intro:'森林的兩晚之後，搬到園區中央。今天留給米菲兔、購物與紀念照，午晚餐都在園內解決。',route:'森林小屋 → 阿姆斯特丹飯店 → 園區中央',map:'Huis Ten Bosch Hotel Amsterdam',steps:[['早餐後','退房與轉交行李','先問飯店行李移送方式；若無移送服務，再自行搬運。','規劃'],['白天','米菲兔主題區、商店與園內午餐','看喜歡的周邊，午餐依所在區域選擇；室內設施作為下雨備案。','規劃','ミッフィー・ワンダースクエア ハウステンボス'],['入住時','米菲兔房・一晚','基本房型，含早餐及備品，¥69,200 已付；入住時間待飯店確認。','已訂','ホテルアムステルダム ハウステンボス'],['夜間','園內晚餐與最後一晚散步','晚餐仍在園區內處理；今天住園區中央，讓回房的路也成為風景。','自由','ハウステンボス']],note:'10/31 中午過後才離開；今晚先整理戰利品，避免退房時才開始塞行李。'},
 {date:'10.31',week:'六',city:'福岡',en:'NAKASU NIGHT',title:'午後回福岡，<br>晚上走進中洲祭。',image:'newotani.jpg',alt:'博多新大谷飯店官方外觀照片',hotel:4,intro:'上午繼續留在豪斯登堡，中午過後再回福岡。入住博多新大谷後前往中洲祭，晚餐以動線方便為優先。',route:'豪斯登堡 → 博多新大谷 → 中洲祭',map:'中洲中央通り 福岡',steps:[['上午至中午','豪斯登堡最後散步與園內午餐','早餐後不急著離開，園內再逛一輪並吃午餐；中午過後才出發。','確認','ハウステンボス'],['午後','返回福岡、前往渡邊通','搭車回博多，再轉往渡邊通；實際班次待訂票時確認。','規劃'],['14:00 後','博多新大谷入住','連住至 11/02，行政雙人房禁菸高樓層，不含早餐。','已訂','Hotel New Otani Hakata'],['夜間','中洲祭（中洲まつり）','官方已公告第 51 回中洲祭於 10/30–10/31 舉行；活動時間與表演細節接近出發時再確認。','確認','中洲中央通り 福岡'],['晚餐','就近吃居酒屋或拉麵','不特別繞路訂遠店，以中洲祭現場、回飯店動線與候位狀況決定。','彈性']],note:'中洲祭日期已核定；晚餐刻意保留彈性，以方便為主。西鐵 Grand 仍需完成取消，新大谷兩晚訂單保留。'},
 {date:'11.01',week:'日',city:'福岡',en:'SHOPPING DAY',title:'一整天購物，<br>用紀念日晚餐收尾。',image:'tenjin.jpg',alt:'福岡天神街景與秋日行道樹',hotel:4,intro:'整天留給福岡購物；19:00 已訂博多 Kagen（博多 かげん）雙人晚餐，從博多站或天神回渡邊通都順路。',route:'新大谷 → 天神・大名・今泉 → 博多站 → 博多 Kagen → 新大谷',map:'博多 かげん 福岡',steps:[['上午','早餐與天神百貨','飯店方案不含早餐，可另購或外出用餐；天神地下街也是雨天動線。','規劃','天神地下街'],['午後','大名、今泉與購物','選物、服飾與獨立小店，整天不另排觀光景點。','確認','福岡市 大名'],['傍晚','博多站補齊伴手禮','地下食品街、阪急與商場依需要選擇；18:30 左右開始往渡邊通方向移動。','規劃','博多駅'],['19:00','博多 Kagen（博多 かげん）','Tabelog 已確認 2 位、可用餐 3 小時。每人 ¥12,100 無類別套餐，另收每人 ¥770 席費；座位未指定，餐費當日店內支付。','已訂','博多 かげん 福岡']],note:'訂位用途填寫「交往紀念日」。Tabelog 系統費共 ¥880 已收取且原則不退；前一天取消收套餐 30%，當天有聯絡 50%，未聯絡 100%。地址：福岡市中央區渡邊通 1-9-2 Central Heights 1F。'},
 {date:'11.02',week:'一',city:'返程',en:'UNTIL NEXT TIME',title:'把秋天收好，<br>我們回家。',image:'airport.jpg',alt:'機場與飛機，沿用原專案配圖',hotel:null,intro:'最後一天不塞景點。早餐、退房、機場，把所有需要排隊的事都留出餘裕。',route:'博多新大谷 → 福岡國際線 → 桃園第二航廈',map:'福岡空港 国際線',steps:[['07:00','早餐、檢查行李','早餐另購或外出；護照、手機、免稅商品與收據再確認。','規劃'],['08:00 左右','退房前往機場','可預約計程車直達國際線；若搭地鐵，需計入國內線至國際線接駁。','規劃'],['09:00 目標','抵達國際線航廈','先辦免稅品確認再託運；這是預留時間，仍以航空公司與機場當日流程為準。','規劃'],['12:15','長榮 BR105 起飛','福岡國際線出發，13:50 抵達桃園第二航廈，均為當地時間。','已開票']],note:'飯店最晚退房為 11:00，但這天要提早離開搭飛機。'}
];
const tasks = [
 {id:'cancel-grand',type:'優先退訂',title:'取消西鐵 Grand',date:'10/31–11/01',note:'你已選博多新大谷。原信：入住前 7 日起收全額，即 10/24 起 100%；確切截止時間回平台確認。',platform:'tripla',url:'https://tripla.ai/',search:'西鐵Grand酒店'},
];
const $ = s => document.querySelector(s);
const yen = n => '¥'+n.toLocaleString('en-US');
const mapLink = q => 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const confirmedMaps=[['武雄・有田',[['武雄溫泉站','武雄温泉駅'],['武雄神社','武雄神社'],['武雄溫泉樓門','武雄温泉楼門'],['有田瓷器城（アリタセラ）','アリタセラ']]],['長崎',[['長崎站','長崎駅'],['大浦天主堂','大浦天主堂'],['長崎原爆資料館','長崎原爆資料館'],['岩永梅壽軒','岩永梅寿軒'],['大阪屋濱町店','大阪屋 浜町店 長崎']]],['豪斯登堡・福岡',[['豪斯登堡','ハウステンボス'],['中洲祭會場周邊','中洲中央通り 福岡'],['博多新大谷','Hotel New Otani Hakata'],['博多 Kagen（博多 かげん）','博多 かげん 福岡']]]];
const stateKey = 'kyushu-2026-cancellation-checklist-v3';
let checked = {},storageOK=true;
try{const stored=JSON.parse(localStorage.getItem(stateKey)||'{}');if(stored&&typeof stored==='object'&&!Array.isArray(stored))checked=stored;}catch{storageOK=false;}
let activeDay=0;
$('#confirmed-maps').innerHTML=confirmedMaps.map(group=>`<p><b>${group[0]}</b><br>${group[1].map(place=>`<a href="${mapLink(place[1])}" target="_blank" rel="noopener noreferrer">${place[0]} ↗</a>`).join(' · ')}</p>`).join('');
function renderDay(index){
 activeDay=Math.max(0,Math.min(9,index));const d=days[activeDay],h=hotels[d.hotel];
 $('#day-stage').innerHTML=`<article class="day-page"><figure class="day-photo"><img src="img/${d.image}" alt="${d.alt}" width="1000" height="1200"><figcaption><span>${d.en}</span><span>${d.city}</span></figcaption><span class="day-big">${String(activeDay+1).padStart(2,'0')}</span></figure><div class="day-copy"><div class="day-label"><span>DAY ${String(activeDay+1).padStart(2,'0')}</span><span>${d.date} / 星期${d.week}</span></div><h3>${d.title}</h3><p class="day-intro">${d.intro}</p><div class="route-note"><span>↗</span>${d.route}</div><ol class="timeline">${d.steps.map(s=>`<li><time>${s[0]}</time><div><h4>${s[1]}<small class="badge ${s[3]==='已訂'||s[3]==='已開票'?'confirmed':''}">${s[3]}</small></h4><p>${s[2]}</p></div></li>`).join('')}</ol><div class="day-note ${d.task?'attention':''}">${d.note}${d.task?' <a href="#tasks">處理待辦 ↗</a>':''}</div><div class="day-bottom">${h?`<a href="#hotel-${d.hotel}" class="sleep-link"><small>今晚住這裡</small><strong>${h.name}</strong></a>`:'<div class="sleep-link"><small>下一站</small><strong>回到溫暖的家</strong></div>'}<a class="map-link" href="${mapLink(d.map)}" target="_blank" rel="noopener noreferrer">開啟地圖 ↗</a></div></div></article>`;
 document.querySelectorAll('.day-rail a').forEach((a,i)=>{if(i===activeDay)a.setAttribute('aria-current','date');else a.removeAttribute('aria-current');});
 $('#prev-day').disabled=activeDay===0;$('#next-day').disabled=activeDay===9;$('#day-position').textContent=String(activeDay+1).padStart(2,'0')+' / 10';
}
$('#day-rail').innerHTML=days.map((d,i)=>`<a href="#day-${i+1}" data-day="${i}" aria-label="第 ${i+1} 天 ${d.date} ${d.city}"><span>${String(i+1).padStart(2,'0')}</span><b>${d.city}</b><small>${d.date}</small></a>`).join('');
$('#hotel-grid').innerHTML=hotels.map((h,i)=>`<article class="hotel-card" id="hotel-${i}"><figure><img src="img/${h.img}" alt="${h.alt}" loading="lazy" width="1000" height="700"><span>${h.nights} NIGHTS</span></figure><div class="hotel-info"><div class="hotel-top"><small>${h.dates}</small><span>保留 ✓</span></div><p class="hotel-en">${h.en}</p><h3>${h.name}</h3><p>${h.room}<br>${h.meals}</p><div class="hotel-price"><strong>${yen(h.price)}</strong><span>${h.payment}</span></div><details><summary>入住資訊與地圖 <span>＋</span></summary><p>${h.check}<br>${h.note}</p><a href="${mapLink(h.query)}" target="_blank" rel="noopener noreferrer">地圖導航 ↗</a> <a href="${h.url}" target="_blank" rel="noopener noreferrer">飯店官網 ↗</a></details></div></article>`).join('');
$('#task-list').innerHTML=tasks.map((t,i)=>`<article class="task-item" data-task="${t.id}"><label class="check-wrap"><input type="checkbox" data-check="${t.id}" ${checked[t.id]===true?'checked':''} aria-label="${t.title}：已收到取消確認或已完成協調"><span aria-hidden="true">✓</span></label><div><div class="task-meta"><span>${t.type}</span><small>${t.date}</small></div><h3>${t.title}</h3><p>${t.note}</p><div class="task-actions"><a href="${t.url}" target="_blank" rel="noopener noreferrer">前往 ${t.platform} ↗</a><button data-copy="${i}">複製郵件搜尋詞</button></div></div></article>`).join('');
function updateTasks(){let done=tasks.filter(t=>checked[t.id]===true).length;$('#task-count').textContent=done+' / '+tasks.length;$('#nav-count').textContent=tasks.length-done;$('#mobile-count').textContent=tasks.length-done;$('#task-fill').style.width=(done/tasks.length*100)+'%';document.querySelectorAll('.task-item').forEach(el=>el.classList.toggle('done',checked[el.dataset.task]===true));if(!storageOK)$('#storage-note').textContent='瀏覽器未允許儲存，勾選僅在這次開啟期間有效；不會取消訂单。';}
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
$('#task-list').addEventListener('change',e=>{if(!e.target.dataset.check)return;checked[e.target.dataset.check]=e.target.checked;try{localStorage.setItem(stateKey,JSON.stringify(checked));}catch{storageOK=false;}updateTasks();toast(e.target.checked?'已記錄處理完成；訂單狀態請以平台確認為準。':'已恢復為待處理。');});
$('#task-list').addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;const term=tasks[Number(b.dataset.copy)].search;try{await navigator.clipboard.writeText(term);toast('已複製：'+term);}catch{toast('搜尋原信：'+term);}});
function dayFromHash(){const m=location.hash.match(/^#day-(\d+)$/);if(m&&Number(m[1])>=1&&Number(m[1])<=10){renderDay(Number(m[1])-1);$('#journey').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return true;}return false;}
window.addEventListener('hashchange',dayFromHash);
$('#prev-day').addEventListener('click',()=>{location.hash='day-'+activeDay;});$('#next-day').addEventListener('click',()=>{location.hash='day-'+(activeDay+2);});
$('#day-rail').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=Math.max(0,Math.min(9,activeDay+(e.key==='ArrowRight'?1:-1)));location.hash='day-'+(next+1);document.querySelectorAll('.day-rail a')[next].focus();}});
$('#all-days-panel').innerHTML=days.map((d,i)=>`<a href="#day-${i+1}"><b>${d.date}</b><span>${d.city}</span><p>${d.title.replace('<br>','')}</p><small>${d.hotel===null?'返程':hotels[d.hotel].name}</small><i>↗</i></a>`).join('');
$('#all-days').addEventListener('click',()=>{let open=$('#all-days-panel').hidden;$('#all-days-panel').hidden=!open;$('#all-days').setAttribute('aria-expanded',String(open));$('#all-days').textContent=open?'收起十天總覽 −':'展開十天總覽 ＋';});
function renderBudget(){let input=$('#extra-budget'),v=Number(input.value);if(!Number.isFinite(v)||v<0||v>2000000){input.setCustomValidity('請輸入 0 至 2,000,000 日圓');return;}input.setCustomValidity('');let sum=357218+12300+22000+v;$('#budget-total').textContent='NT$ '+Math.round(sum*Number($('#budget-rate').value)+9250).toLocaleString('en-US');$('#budget-jpy').textContent='日本境內 '+yen(sum)+' ＋ 機票費用暫估';$('#extra-value').textContent=yen(v);}
$('#budget-rate').addEventListener('change',renderBudget);$('#extra-budget').addEventListener('input',renderBudget);
function downloadReminder(){const remaining=tasks.filter(t=>!checked[t.id]);if(!remaining.length){toast('所有待辦均已勾選完成。');return;}const esc=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const dt=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Kyushu Journal//Trip Reminder//ZH','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:kyushu-cancel-20261016@personal-trip','DTSTAMP:'+dt,'DTSTART:20261016T010000Z','DTEND:20261016T013000Z','SUMMARY:'+esc('九州旅行：取消西鐵 Grand'),'DESCRIPTION:'+esc('其餘備案住宿與博多紀念日晚餐已有取消確認；此事件不會取消訂單。\n'+remaining.map(t=>t.title+' '+t.date+'；'+t.note).join('\n')),'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:請完成九州退訂待辦','END:VALARM','END:VEVENT','END:VCALENDAR'];const folded=lines.map(line=>{let result='',bytes=0;for(const ch of line){const size=new TextEncoder().encode(ch).length;if(bytes+size>73){result+='\r\n ';bytes=1;}result+=ch;bytes+=size;}return result;}).join('\r\n')+'\r\n';const url=URL.createObjectURL(new Blob([folded],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='九州退訂提醒-20261016.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('提醒檔已下載；請匯入你的行事曆才會通知。');}
$('#download-reminder').addEventListener('click',downloadReminder);$('#print-trip').addEventListener('click',()=>{window.print();});
const printSummary=document.createElement('section');printSummary.className='print-summary';printSummary.innerHTML='<h2>十天行程總覽</h2>'+days.map((d,i)=>`<article><h3>${d.date} ${d.city}・${d.title.replace('<br>','')}</h3><p>${d.route}</p>${d.steps.map(s=>`<p>${s[0]}　${s[1]}：${s[2]}</p>`).join('')}<p>${d.hotel===null?'返程':hotels[d.hotel].name}。${d.note}</p></article>`).join('');$('#journey').appendChild(printSummary);
updateTasks();renderBudget();renderDay(0);dayFromHash();
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.topbar nav a,.mobile-nav a').forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}});},{rootMargin:'-15% 0px -60% 0px'});['journey','stays','tasks','guide','budget'].forEach(id=>observer.observe(document.getElementById(id)));}
